### ISSUE TITLE
TZ issue?

### ISSUE THREAD

**Issue by Alex-CodeLab** [spapas/django-test-rq#1]
The Scheduled tasks seem to have a 2 hour delay before they get executed.
I think this is timezone related  (i'm UTC+2).

**Comment by spapas** [comment]
Hello @allox. Hmmm from what I see, I am using the following to set the schedule times:

```
job = scheduler.schedule(
                scheduled_time=datetime.datetime.now(),
                func=scheduled_get_url_words,
                args=[url],
                interval=schedule_interval,
                repeat=schedule_times,
            )
```

So I use `datetime.datetime.now() (which returns the current local time), but since my vagrant box *also* has UTC time,`now()`` will the correct current time and execute the first instance of the scheduled task immediately (since the scheduled_time parameter is the UTC time https://github.com/ui/rq-scheduler#periodic--repeated-jobs).

In your case, since you are UTC+3, the `now()` function will probably the local time which, which, `schedule` will think that is UTC so the task will be executed after three hours (!)

What I propose is to use the `datetime.datetime.utcnow` (https://docs.python.org/2/library/datetime.html#datetime.datetime.utcnow) function that will return the  current time in UTC (or just convert the local time you have to UTC -- http://stackoverflow.com/questions/79797/how-do-i-convert-local-time-to-utc-in-python)
